// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { QueryParamsResponse } from "./types/zigchain/dex/query";
import { QueryAllPoolUidsRequest } from "./types/zigchain/dex/query";
import { MsgUpdateParamsResponse } from "./types/zigchain/dex/tx";
import { MsgCreatePool } from "./types/zigchain/dex/tx";
import { QueryParamsRequest } from "./types/zigchain/dex/query";
import { QueryGetPoolRequest } from "./types/zigchain/dex/query";
import { QueryGetPoolResponse } from "./types/zigchain/dex/query";
import { QueryGetPoolUidRequest } from "./types/zigchain/dex/query";
import { QuerySwapInRequest } from "./types/zigchain/dex/query";
import { Params } from "./types/zigchain/dex/params";
import { PoolPair } from "./types/zigchain/dex/pool";
import { DexPacketData } from "./types/zigchain/dex/packet";
import { QueryAllPoolRequest } from "./types/zigchain/dex/query";
import { QueryGetPoolsMetaRequest } from "./types/zigchain/dex/query";
import { PoolUids } from "./types/zigchain/dex/pool_uids";
import { MsgRemoveLiquidity } from "./types/zigchain/dex/tx";
import { MsgRemoveLiquidityResponse } from "./types/zigchain/dex/tx";
import { PoolsMeta } from "./types/zigchain/dex/pools_meta";
import { Pool } from "./types/zigchain/dex/pool";
import { NoData } from "./types/zigchain/dex/packet";
import { QuerySwapInResponse } from "./types/zigchain/dex/query";
import { MsgAddLiquidityResponse } from "./types/zigchain/dex/tx";
import { QueryAllPoolUidsResponse } from "./types/zigchain/dex/query";
import { QueryGetPoolUidResponse } from "./types/zigchain/dex/query";
import { MsgSwap } from "./types/zigchain/dex/tx";
import { MsgAddLiquidity } from "./types/zigchain/dex/tx";
import { GenesisState } from "./types/zigchain/dex/genesis";
import { QueryAllPoolResponse } from "./types/zigchain/dex/query";
import { QueryGetPoolsMetaResponse } from "./types/zigchain/dex/query";
import { MsgUpdateParams } from "./types/zigchain/dex/tx";
import { MsgCreatePoolResponse } from "./types/zigchain/dex/tx";
import { MsgSwapResponse } from "./types/zigchain/dex/tx";


export { QueryParamsResponse, QueryAllPoolUidsRequest, MsgUpdateParamsResponse, MsgCreatePool, QueryParamsRequest, QueryGetPoolRequest, QueryGetPoolResponse, QueryGetPoolUidRequest, QuerySwapInRequest, Params, PoolPair, DexPacketData, QueryAllPoolRequest, QueryGetPoolsMetaRequest, PoolUids, MsgRemoveLiquidity, MsgRemoveLiquidityResponse, PoolsMeta, Pool, NoData, QuerySwapInResponse, MsgAddLiquidityResponse, QueryAllPoolUidsResponse, QueryGetPoolUidResponse, MsgSwap, MsgAddLiquidity, GenesisState, QueryAllPoolResponse, QueryGetPoolsMetaResponse, MsgUpdateParams, MsgCreatePoolResponse, MsgSwapResponse };

type sendQueryParamsResponseParams = {
  value: QueryParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllPoolUidsRequestParams = {
  value: QueryAllPoolUidsRequest,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreatePoolParams = {
  value: MsgCreatePool,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsRequestParams = {
  value: QueryParamsRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetPoolRequestParams = {
  value: QueryGetPoolRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetPoolResponseParams = {
  value: QueryGetPoolResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetPoolUidRequestParams = {
  value: QueryGetPoolUidRequest,
  fee?: StdFee,
  memo?: string
};

type sendQuerySwapInRequestParams = {
  value: QuerySwapInRequest,
  fee?: StdFee,
  memo?: string
};

type sendParamsParams = {
  value: Params,
  fee?: StdFee,
  memo?: string
};

type sendPoolPairParams = {
  value: PoolPair,
  fee?: StdFee,
  memo?: string
};

type sendDexPacketDataParams = {
  value: DexPacketData,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllPoolRequestParams = {
  value: QueryAllPoolRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetPoolsMetaRequestParams = {
  value: QueryGetPoolsMetaRequest,
  fee?: StdFee,
  memo?: string
};

type sendPoolUidsParams = {
  value: PoolUids,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveLiquidityParams = {
  value: MsgRemoveLiquidity,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveLiquidityResponseParams = {
  value: MsgRemoveLiquidityResponse,
  fee?: StdFee,
  memo?: string
};

type sendPoolsMetaParams = {
  value: PoolsMeta,
  fee?: StdFee,
  memo?: string
};

type sendPoolParams = {
  value: Pool,
  fee?: StdFee,
  memo?: string
};

type sendNoDataParams = {
  value: NoData,
  fee?: StdFee,
  memo?: string
};

type sendQuerySwapInResponseParams = {
  value: QuerySwapInResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddLiquidityResponseParams = {
  value: MsgAddLiquidityResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllPoolUidsResponseParams = {
  value: QueryAllPoolUidsResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetPoolUidResponseParams = {
  value: QueryGetPoolUidResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgSwapParams = {
  value: MsgSwap,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddLiquidityParams = {
  value: MsgAddLiquidity,
  fee?: StdFee,
  memo?: string
};

type sendGenesisStateParams = {
  value: GenesisState,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllPoolResponseParams = {
  value: QueryAllPoolResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetPoolsMetaResponseParams = {
  value: QueryGetPoolsMetaResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreatePoolResponseParams = {
  value: MsgCreatePoolResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgSwapResponseParams = {
  value: MsgSwapResponse,
  fee?: StdFee,
  memo?: string
};


type queryParamsResponseParams = {
  value: QueryParamsResponse,
};

type queryAllPoolUidsRequestParams = {
  value: QueryAllPoolUidsRequest,
};

type msgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
};

type msgCreatePoolParams = {
  value: MsgCreatePool,
};

type queryParamsRequestParams = {
  value: QueryParamsRequest,
};

type queryGetPoolRequestParams = {
  value: QueryGetPoolRequest,
};

type queryGetPoolResponseParams = {
  value: QueryGetPoolResponse,
};

type queryGetPoolUidRequestParams = {
  value: QueryGetPoolUidRequest,
};

type querySwapInRequestParams = {
  value: QuerySwapInRequest,
};

type paramsParams = {
  value: Params,
};

type poolPairParams = {
  value: PoolPair,
};

type dexPacketDataParams = {
  value: DexPacketData,
};

type queryAllPoolRequestParams = {
  value: QueryAllPoolRequest,
};

type queryGetPoolsMetaRequestParams = {
  value: QueryGetPoolsMetaRequest,
};

type poolUidsParams = {
  value: PoolUids,
};

type msgRemoveLiquidityParams = {
  value: MsgRemoveLiquidity,
};

type msgRemoveLiquidityResponseParams = {
  value: MsgRemoveLiquidityResponse,
};

type poolsMetaParams = {
  value: PoolsMeta,
};

type poolParams = {
  value: Pool,
};

type noDataParams = {
  value: NoData,
};

type querySwapInResponseParams = {
  value: QuerySwapInResponse,
};

type msgAddLiquidityResponseParams = {
  value: MsgAddLiquidityResponse,
};

type queryAllPoolUidsResponseParams = {
  value: QueryAllPoolUidsResponse,
};

type queryGetPoolUidResponseParams = {
  value: QueryGetPoolUidResponse,
};

type msgSwapParams = {
  value: MsgSwap,
};

type msgAddLiquidityParams = {
  value: MsgAddLiquidity,
};

type genesisStateParams = {
  value: GenesisState,
};

type queryAllPoolResponseParams = {
  value: QueryAllPoolResponse,
};

type queryGetPoolsMetaResponseParams = {
  value: QueryGetPoolsMetaResponse,
};

type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgCreatePoolResponseParams = {
  value: MsgCreatePoolResponse,
};

type msgSwapResponseParams = {
  value: MsgSwapResponse,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendQueryParamsResponse({ value, fee, memo }: sendQueryParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsResponse({ value: QueryParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllPoolUidsRequest({ value, fee, memo }: sendQueryAllPoolUidsRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllPoolUidsRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllPoolUidsRequest({ value: QueryAllPoolUidsRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllPoolUidsRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParamsResponse({ value, fee, memo }: sendMsgUpdateParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParamsResponse({ value: MsgUpdateParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreatePool({ value, fee, memo }: sendMsgCreatePoolParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreatePool: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreatePool({ value: MsgCreatePool.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreatePool: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsRequest({ value, fee, memo }: sendQueryParamsRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsRequest({ value: QueryParamsRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetPoolRequest({ value, fee, memo }: sendQueryGetPoolRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetPoolRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetPoolRequest({ value: QueryGetPoolRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetPoolRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetPoolResponse({ value, fee, memo }: sendQueryGetPoolResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetPoolResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetPoolResponse({ value: QueryGetPoolResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetPoolResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetPoolUidRequest({ value, fee, memo }: sendQueryGetPoolUidRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetPoolUidRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetPoolUidRequest({ value: QueryGetPoolUidRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetPoolUidRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQuerySwapInRequest({ value, fee, memo }: sendQuerySwapInRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQuerySwapInRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.querySwapInRequest({ value: QuerySwapInRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQuerySwapInRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendParams({ value, fee, memo }: sendParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.params({ value: Params.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendPoolPair({ value, fee, memo }: sendPoolPairParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendPoolPair: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.poolPair({ value: PoolPair.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendPoolPair: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendDexPacketData({ value, fee, memo }: sendDexPacketDataParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendDexPacketData: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.dexPacketData({ value: DexPacketData.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendDexPacketData: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllPoolRequest({ value, fee, memo }: sendQueryAllPoolRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllPoolRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllPoolRequest({ value: QueryAllPoolRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllPoolRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetPoolsMetaRequest({ value, fee, memo }: sendQueryGetPoolsMetaRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetPoolsMetaRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetPoolsMetaRequest({ value: QueryGetPoolsMetaRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetPoolsMetaRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendPoolUids({ value, fee, memo }: sendPoolUidsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendPoolUids: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.poolUids({ value: PoolUids.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendPoolUids: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveLiquidity({ value, fee, memo }: sendMsgRemoveLiquidityParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveLiquidity: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRemoveLiquidity({ value: MsgRemoveLiquidity.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveLiquidity: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveLiquidityResponse({ value, fee, memo }: sendMsgRemoveLiquidityResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveLiquidityResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRemoveLiquidityResponse({ value: MsgRemoveLiquidityResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveLiquidityResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendPoolsMeta({ value, fee, memo }: sendPoolsMetaParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendPoolsMeta: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.poolsMeta({ value: PoolsMeta.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendPoolsMeta: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendPool({ value, fee, memo }: sendPoolParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendPool: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.pool({ value: Pool.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendPool: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendNoData({ value, fee, memo }: sendNoDataParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendNoData: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.noData({ value: NoData.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendNoData: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQuerySwapInResponse({ value, fee, memo }: sendQuerySwapInResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQuerySwapInResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.querySwapInResponse({ value: QuerySwapInResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQuerySwapInResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddLiquidityResponse({ value, fee, memo }: sendMsgAddLiquidityResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddLiquidityResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgAddLiquidityResponse({ value: MsgAddLiquidityResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddLiquidityResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllPoolUidsResponse({ value, fee, memo }: sendQueryAllPoolUidsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllPoolUidsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllPoolUidsResponse({ value: QueryAllPoolUidsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllPoolUidsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetPoolUidResponse({ value, fee, memo }: sendQueryGetPoolUidResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetPoolUidResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetPoolUidResponse({ value: QueryGetPoolUidResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetPoolUidResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSwap({ value, fee, memo }: sendMsgSwapParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSwap: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgSwap({ value: MsgSwap.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSwap: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddLiquidity({ value, fee, memo }: sendMsgAddLiquidityParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddLiquidity: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgAddLiquidity({ value: MsgAddLiquidity.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddLiquidity: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendGenesisState({ value, fee, memo }: sendGenesisStateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendGenesisState: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.genesisState({ value: GenesisState.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendGenesisState: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllPoolResponse({ value, fee, memo }: sendQueryAllPoolResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllPoolResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllPoolResponse({ value: QueryAllPoolResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllPoolResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetPoolsMetaResponse({ value, fee, memo }: sendQueryGetPoolsMetaResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetPoolsMetaResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetPoolsMetaResponse({ value: QueryGetPoolsMetaResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetPoolsMetaResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreatePoolResponse({ value, fee, memo }: sendMsgCreatePoolResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreatePoolResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreatePoolResponse({ value: MsgCreatePoolResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreatePoolResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSwapResponse({ value, fee, memo }: sendMsgSwapResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSwapResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgSwapResponse({ value: MsgSwapResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSwapResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		queryParamsResponse({ value }: queryParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryParamsResponse", value: QueryParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		queryAllPoolUidsRequest({ value }: queryAllPoolUidsRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryAllPoolUidsRequest", value: QueryAllPoolUidsRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllPoolUidsRequest: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParamsResponse({ value }: msgUpdateParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.MsgUpdateParamsResponse", value: MsgUpdateParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		msgCreatePool({ value }: msgCreatePoolParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.MsgCreatePool", value: MsgCreatePool.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreatePool: Could not create message: ' + e.message)
			}
		},
		
		queryParamsRequest({ value }: queryParamsRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryParamsRequest", value: QueryParamsRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetPoolRequest({ value }: queryGetPoolRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryGetPoolRequest", value: QueryGetPoolRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetPoolRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetPoolResponse({ value }: queryGetPoolResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryGetPoolResponse", value: QueryGetPoolResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetPoolResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetPoolUidRequest({ value }: queryGetPoolUidRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryGetPoolUidRequest", value: QueryGetPoolUidRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetPoolUidRequest: Could not create message: ' + e.message)
			}
		},
		
		querySwapInRequest({ value }: querySwapInRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QuerySwapInRequest", value: QuerySwapInRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QuerySwapInRequest: Could not create message: ' + e.message)
			}
		},
		
		params({ value }: paramsParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.Params", value: Params.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Params: Could not create message: ' + e.message)
			}
		},
		
		poolPair({ value }: poolPairParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.PoolPair", value: PoolPair.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:PoolPair: Could not create message: ' + e.message)
			}
		},
		
		dexPacketData({ value }: dexPacketDataParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.DexPacketData", value: DexPacketData.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:DexPacketData: Could not create message: ' + e.message)
			}
		},
		
		queryAllPoolRequest({ value }: queryAllPoolRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryAllPoolRequest", value: QueryAllPoolRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllPoolRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetPoolsMetaRequest({ value }: queryGetPoolsMetaRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryGetPoolsMetaRequest", value: QueryGetPoolsMetaRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetPoolsMetaRequest: Could not create message: ' + e.message)
			}
		},
		
		poolUids({ value }: poolUidsParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.PoolUids", value: PoolUids.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:PoolUids: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveLiquidity({ value }: msgRemoveLiquidityParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.MsgRemoveLiquidity", value: MsgRemoveLiquidity.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveLiquidity: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveLiquidityResponse({ value }: msgRemoveLiquidityResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.MsgRemoveLiquidityResponse", value: MsgRemoveLiquidityResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveLiquidityResponse: Could not create message: ' + e.message)
			}
		},
		
		poolsMeta({ value }: poolsMetaParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.PoolsMeta", value: PoolsMeta.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:PoolsMeta: Could not create message: ' + e.message)
			}
		},
		
		pool({ value }: poolParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.Pool", value: Pool.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Pool: Could not create message: ' + e.message)
			}
		},
		
		noData({ value }: noDataParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.NoData", value: NoData.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:NoData: Could not create message: ' + e.message)
			}
		},
		
		querySwapInResponse({ value }: querySwapInResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QuerySwapInResponse", value: QuerySwapInResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QuerySwapInResponse: Could not create message: ' + e.message)
			}
		},
		
		msgAddLiquidityResponse({ value }: msgAddLiquidityResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.MsgAddLiquidityResponse", value: MsgAddLiquidityResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddLiquidityResponse: Could not create message: ' + e.message)
			}
		},
		
		queryAllPoolUidsResponse({ value }: queryAllPoolUidsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryAllPoolUidsResponse", value: QueryAllPoolUidsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllPoolUidsResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetPoolUidResponse({ value }: queryGetPoolUidResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryGetPoolUidResponse", value: QueryGetPoolUidResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetPoolUidResponse: Could not create message: ' + e.message)
			}
		},
		
		msgSwap({ value }: msgSwapParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.MsgSwap", value: MsgSwap.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSwap: Could not create message: ' + e.message)
			}
		},
		
		msgAddLiquidity({ value }: msgAddLiquidityParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.MsgAddLiquidity", value: MsgAddLiquidity.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddLiquidity: Could not create message: ' + e.message)
			}
		},
		
		genesisState({ value }: genesisStateParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.GenesisState", value: GenesisState.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:GenesisState: Could not create message: ' + e.message)
			}
		},
		
		queryAllPoolResponse({ value }: queryAllPoolResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryAllPoolResponse", value: QueryAllPoolResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllPoolResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetPoolsMetaResponse({ value }: queryGetPoolsMetaResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.QueryGetPoolsMetaResponse", value: QueryGetPoolsMetaResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetPoolsMetaResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgCreatePoolResponse({ value }: msgCreatePoolResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.MsgCreatePoolResponse", value: MsgCreatePoolResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreatePoolResponse: Could not create message: ' + e.message)
			}
		},
		
		msgSwapResponse({ value }: msgSwapResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.dex.MsgSwapResponse", value: MsgSwapResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSwapResponse: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			ZigchainDex: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;