// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { QueryAllDenomsByAdminRequest } from "./types/zigchain/factory/query";
import { MsgUpdateDenomMaxSupplyResponse } from "./types/zigchain/factory/tx";
import { MsgBurnTokens } from "./types/zigchain/factory/tx";
import { QueryDenomByAdminRequest } from "./types/zigchain/factory/query";
import { QueryAllDenomAuthRequest } from "./types/zigchain/factory/query";
import { MsgUpdateDenomAuth } from "./types/zigchain/factory/tx";
import { MsgUpdateDenomURI } from "./types/zigchain/factory/tx";
import { MsgUpdateDenomMetadataAuth } from "./types/zigchain/factory/tx";
import { MsgSetDenomMetadataResponse } from "./types/zigchain/factory/tx";
import { Denom } from "./types/zigchain/factory/denom";
import { QueryDenomByAdminResponse } from "./types/zigchain/factory/query";
import { MsgUpdateDenomAuthResponse } from "./types/zigchain/factory/tx";
import { MsgUpdateDenomMaxSupply } from "./types/zigchain/factory/tx";
import { MsgUpdateDenomMetadataAuthResponse } from "./types/zigchain/factory/tx";
import { Params } from "./types/zigchain/factory/params";
import { QueryGetDenomAuthRequest } from "./types/zigchain/factory/query";
import { MsgMintAndSendTokensResponse } from "./types/zigchain/factory/tx";
import { MsgSetDenomMetadata } from "./types/zigchain/factory/tx";
import { DenomAuth } from "./types/zigchain/factory/denom_auth";
import { MsgMintAndSendTokens } from "./types/zigchain/factory/tx";
import { GenesisState } from "./types/zigchain/factory/genesis";
import { QueryAllDenomRequest } from "./types/zigchain/factory/query";
import { QueryAllDenomResponse } from "./types/zigchain/factory/query";
import { QueryDenomAuthResponse } from "./types/zigchain/factory/query";
import { MsgUpdateParams } from "./types/zigchain/factory/tx";
import { MsgCreateDenom } from "./types/zigchain/factory/tx";
import { MsgCreateDenomResponse } from "./types/zigchain/factory/tx";
import { MsgUpdateDenomURIResponse } from "./types/zigchain/factory/tx";
import { QueryParamsResponse } from "./types/zigchain/factory/query";
import { QueryGetDenomRequest } from "./types/zigchain/factory/query";
import { QueryAllDenomsByAdminResponse } from "./types/zigchain/factory/query";
import { QueryAllDenomAuthResponse } from "./types/zigchain/factory/query";
import { QueryParamsRequest } from "./types/zigchain/factory/query";
import { QueryDenomResponse } from "./types/zigchain/factory/query";
import { MsgUpdateParamsResponse } from "./types/zigchain/factory/tx";
import { MsgBurnTokensResponse } from "./types/zigchain/factory/tx";

import { DenomUnit as typeDenomUnit} from "./types"
import { Metadata as typeMetadata} from "./types"

export { QueryAllDenomsByAdminRequest, MsgUpdateDenomMaxSupplyResponse, MsgBurnTokens, QueryDenomByAdminRequest, QueryAllDenomAuthRequest, MsgUpdateDenomAuth, MsgUpdateDenomURI, MsgUpdateDenomMetadataAuth, MsgSetDenomMetadataResponse, Denom, QueryDenomByAdminResponse, MsgUpdateDenomAuthResponse, MsgUpdateDenomMaxSupply, MsgUpdateDenomMetadataAuthResponse, Params, QueryGetDenomAuthRequest, MsgMintAndSendTokensResponse, MsgSetDenomMetadata, DenomAuth, MsgMintAndSendTokens, GenesisState, QueryAllDenomRequest, QueryAllDenomResponse, QueryDenomAuthResponse, MsgUpdateParams, MsgCreateDenom, MsgCreateDenomResponse, MsgUpdateDenomURIResponse, QueryParamsResponse, QueryGetDenomRequest, QueryAllDenomsByAdminResponse, QueryAllDenomAuthResponse, QueryParamsRequest, QueryDenomResponse, MsgUpdateParamsResponse, MsgBurnTokensResponse };

type sendQueryAllDenomsByAdminRequestParams = {
  value: QueryAllDenomsByAdminRequest,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDenomMaxSupplyResponseParams = {
  value: MsgUpdateDenomMaxSupplyResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgBurnTokensParams = {
  value: MsgBurnTokens,
  fee?: StdFee,
  memo?: string
};

type sendQueryDenomByAdminRequestParams = {
  value: QueryDenomByAdminRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllDenomAuthRequestParams = {
  value: QueryAllDenomAuthRequest,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDenomAuthParams = {
  value: MsgUpdateDenomAuth,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDenomURIParams = {
  value: MsgUpdateDenomURI,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDenomMetadataAuthParams = {
  value: MsgUpdateDenomMetadataAuth,
  fee?: StdFee,
  memo?: string
};

type sendMsgSetDenomMetadataResponseParams = {
  value: MsgSetDenomMetadataResponse,
  fee?: StdFee,
  memo?: string
};

type sendDenomParams = {
  value: Denom,
  fee?: StdFee,
  memo?: string
};

type sendQueryDenomByAdminResponseParams = {
  value: QueryDenomByAdminResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDenomAuthResponseParams = {
  value: MsgUpdateDenomAuthResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDenomMaxSupplyParams = {
  value: MsgUpdateDenomMaxSupply,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDenomMetadataAuthResponseParams = {
  value: MsgUpdateDenomMetadataAuthResponse,
  fee?: StdFee,
  memo?: string
};

type sendParamsParams = {
  value: Params,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetDenomAuthRequestParams = {
  value: QueryGetDenomAuthRequest,
  fee?: StdFee,
  memo?: string
};

type sendMsgMintAndSendTokensResponseParams = {
  value: MsgMintAndSendTokensResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgSetDenomMetadataParams = {
  value: MsgSetDenomMetadata,
  fee?: StdFee,
  memo?: string
};

type sendDenomAuthParams = {
  value: DenomAuth,
  fee?: StdFee,
  memo?: string
};

type sendMsgMintAndSendTokensParams = {
  value: MsgMintAndSendTokens,
  fee?: StdFee,
  memo?: string
};

type sendGenesisStateParams = {
  value: GenesisState,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllDenomRequestParams = {
  value: QueryAllDenomRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllDenomResponseParams = {
  value: QueryAllDenomResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryDenomAuthResponseParams = {
  value: QueryDenomAuthResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateDenomParams = {
  value: MsgCreateDenom,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateDenomResponseParams = {
  value: MsgCreateDenomResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDenomURIResponseParams = {
  value: MsgUpdateDenomURIResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsResponseParams = {
  value: QueryParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetDenomRequestParams = {
  value: QueryGetDenomRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllDenomsByAdminResponseParams = {
  value: QueryAllDenomsByAdminResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllDenomAuthResponseParams = {
  value: QueryAllDenomAuthResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsRequestParams = {
  value: QueryParamsRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryDenomResponseParams = {
  value: QueryDenomResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgBurnTokensResponseParams = {
  value: MsgBurnTokensResponse,
  fee?: StdFee,
  memo?: string
};


type queryAllDenomsByAdminRequestParams = {
  value: QueryAllDenomsByAdminRequest,
};

type msgUpdateDenomMaxSupplyResponseParams = {
  value: MsgUpdateDenomMaxSupplyResponse,
};

type msgBurnTokensParams = {
  value: MsgBurnTokens,
};

type queryDenomByAdminRequestParams = {
  value: QueryDenomByAdminRequest,
};

type queryAllDenomAuthRequestParams = {
  value: QueryAllDenomAuthRequest,
};

type msgUpdateDenomAuthParams = {
  value: MsgUpdateDenomAuth,
};

type msgUpdateDenomUriParams = {
  value: MsgUpdateDenomURI,
};

type msgUpdateDenomMetadataAuthParams = {
  value: MsgUpdateDenomMetadataAuth,
};

type msgSetDenomMetadataResponseParams = {
  value: MsgSetDenomMetadataResponse,
};

type denomParams = {
  value: Denom,
};

type queryDenomByAdminResponseParams = {
  value: QueryDenomByAdminResponse,
};

type msgUpdateDenomAuthResponseParams = {
  value: MsgUpdateDenomAuthResponse,
};

type msgUpdateDenomMaxSupplyParams = {
  value: MsgUpdateDenomMaxSupply,
};

type msgUpdateDenomMetadataAuthResponseParams = {
  value: MsgUpdateDenomMetadataAuthResponse,
};

type paramsParams = {
  value: Params,
};

type queryGetDenomAuthRequestParams = {
  value: QueryGetDenomAuthRequest,
};

type msgMintAndSendTokensResponseParams = {
  value: MsgMintAndSendTokensResponse,
};

type msgSetDenomMetadataParams = {
  value: MsgSetDenomMetadata,
};

type denomAuthParams = {
  value: DenomAuth,
};

type msgMintAndSendTokensParams = {
  value: MsgMintAndSendTokens,
};

type genesisStateParams = {
  value: GenesisState,
};

type queryAllDenomRequestParams = {
  value: QueryAllDenomRequest,
};

type queryAllDenomResponseParams = {
  value: QueryAllDenomResponse,
};

type queryDenomAuthResponseParams = {
  value: QueryDenomAuthResponse,
};

type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgCreateDenomParams = {
  value: MsgCreateDenom,
};

type msgCreateDenomResponseParams = {
  value: MsgCreateDenomResponse,
};

type msgUpdateDenomUriresponseParams = {
  value: MsgUpdateDenomURIResponse,
};

type queryParamsResponseParams = {
  value: QueryParamsResponse,
};

type queryGetDenomRequestParams = {
  value: QueryGetDenomRequest,
};

type queryAllDenomsByAdminResponseParams = {
  value: QueryAllDenomsByAdminResponse,
};

type queryAllDenomAuthResponseParams = {
  value: QueryAllDenomAuthResponse,
};

type queryParamsRequestParams = {
  value: QueryParamsRequest,
};

type queryDenomResponseParams = {
  value: QueryDenomResponse,
};

type msgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
};

type msgBurnTokensResponseParams = {
  value: MsgBurnTokensResponse,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendQueryAllDenomsByAdminRequest({ value, fee, memo }: sendQueryAllDenomsByAdminRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllDenomsByAdminRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllDenomsByAdminRequest({ value: QueryAllDenomsByAdminRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllDenomsByAdminRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDenomMaxSupplyResponse({ value, fee, memo }: sendMsgUpdateDenomMaxSupplyResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDenomMaxSupplyResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateDenomMaxSupplyResponse({ value: MsgUpdateDenomMaxSupplyResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDenomMaxSupplyResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgBurnTokens({ value, fee, memo }: sendMsgBurnTokensParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgBurnTokens: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgBurnTokens({ value: MsgBurnTokens.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgBurnTokens: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryDenomByAdminRequest({ value, fee, memo }: sendQueryDenomByAdminRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryDenomByAdminRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryDenomByAdminRequest({ value: QueryDenomByAdminRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryDenomByAdminRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllDenomAuthRequest({ value, fee, memo }: sendQueryAllDenomAuthRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllDenomAuthRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllDenomAuthRequest({ value: QueryAllDenomAuthRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllDenomAuthRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDenomAuth({ value, fee, memo }: sendMsgUpdateDenomAuthParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDenomAuth: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateDenomAuth({ value: MsgUpdateDenomAuth.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDenomAuth: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDenomURI({ value, fee, memo }: sendMsgUpdateDenomURIParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDenomURI: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateDenomUri({ value: MsgUpdateDenomURI.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDenomURI: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDenomMetadataAuth({ value, fee, memo }: sendMsgUpdateDenomMetadataAuthParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDenomMetadataAuth: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateDenomMetadataAuth({ value: MsgUpdateDenomMetadataAuth.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDenomMetadataAuth: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSetDenomMetadataResponse({ value, fee, memo }: sendMsgSetDenomMetadataResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSetDenomMetadataResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgSetDenomMetadataResponse({ value: MsgSetDenomMetadataResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSetDenomMetadataResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendDenom({ value, fee, memo }: sendDenomParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendDenom: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.denom({ value: Denom.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendDenom: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryDenomByAdminResponse({ value, fee, memo }: sendQueryDenomByAdminResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryDenomByAdminResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryDenomByAdminResponse({ value: QueryDenomByAdminResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryDenomByAdminResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDenomAuthResponse({ value, fee, memo }: sendMsgUpdateDenomAuthResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDenomAuthResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateDenomAuthResponse({ value: MsgUpdateDenomAuthResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDenomAuthResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDenomMaxSupply({ value, fee, memo }: sendMsgUpdateDenomMaxSupplyParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDenomMaxSupply: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateDenomMaxSupply({ value: MsgUpdateDenomMaxSupply.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDenomMaxSupply: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDenomMetadataAuthResponse({ value, fee, memo }: sendMsgUpdateDenomMetadataAuthResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDenomMetadataAuthResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateDenomMetadataAuthResponse({ value: MsgUpdateDenomMetadataAuthResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDenomMetadataAuthResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendParams({ value, fee, memo }: sendParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.params({ value: Params.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetDenomAuthRequest({ value, fee, memo }: sendQueryGetDenomAuthRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetDenomAuthRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetDenomAuthRequest({ value: QueryGetDenomAuthRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetDenomAuthRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgMintAndSendTokensResponse({ value, fee, memo }: sendMsgMintAndSendTokensResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgMintAndSendTokensResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgMintAndSendTokensResponse({ value: MsgMintAndSendTokensResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgMintAndSendTokensResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSetDenomMetadata({ value, fee, memo }: sendMsgSetDenomMetadataParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSetDenomMetadata: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgSetDenomMetadata({ value: MsgSetDenomMetadata.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSetDenomMetadata: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendDenomAuth({ value, fee, memo }: sendDenomAuthParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendDenomAuth: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.denomAuth({ value: DenomAuth.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendDenomAuth: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgMintAndSendTokens({ value, fee, memo }: sendMsgMintAndSendTokensParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgMintAndSendTokens: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgMintAndSendTokens({ value: MsgMintAndSendTokens.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgMintAndSendTokens: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendGenesisState({ value, fee, memo }: sendGenesisStateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendGenesisState: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.genesisState({ value: GenesisState.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendGenesisState: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllDenomRequest({ value, fee, memo }: sendQueryAllDenomRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllDenomRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllDenomRequest({ value: QueryAllDenomRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllDenomRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllDenomResponse({ value, fee, memo }: sendQueryAllDenomResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllDenomResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllDenomResponse({ value: QueryAllDenomResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllDenomResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryDenomAuthResponse({ value, fee, memo }: sendQueryDenomAuthResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryDenomAuthResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryDenomAuthResponse({ value: QueryDenomAuthResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryDenomAuthResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateDenom({ value, fee, memo }: sendMsgCreateDenomParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateDenom: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreateDenom({ value: MsgCreateDenom.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateDenom: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateDenomResponse({ value, fee, memo }: sendMsgCreateDenomResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateDenomResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreateDenomResponse({ value: MsgCreateDenomResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateDenomResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDenomURIResponse({ value, fee, memo }: sendMsgUpdateDenomURIResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDenomURIResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateDenomUriresponse({ value: MsgUpdateDenomURIResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDenomURIResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsResponse({ value, fee, memo }: sendQueryParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsResponse({ value: QueryParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetDenomRequest({ value, fee, memo }: sendQueryGetDenomRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetDenomRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetDenomRequest({ value: QueryGetDenomRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetDenomRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllDenomsByAdminResponse({ value, fee, memo }: sendQueryAllDenomsByAdminResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllDenomsByAdminResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllDenomsByAdminResponse({ value: QueryAllDenomsByAdminResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllDenomsByAdminResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllDenomAuthResponse({ value, fee, memo }: sendQueryAllDenomAuthResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllDenomAuthResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllDenomAuthResponse({ value: QueryAllDenomAuthResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllDenomAuthResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsRequest({ value, fee, memo }: sendQueryParamsRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsRequest({ value: QueryParamsRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryDenomResponse({ value, fee, memo }: sendQueryDenomResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryDenomResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryDenomResponse({ value: QueryDenomResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryDenomResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParamsResponse({ value, fee, memo }: sendMsgUpdateParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParamsResponse({ value: MsgUpdateParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgBurnTokensResponse({ value, fee, memo }: sendMsgBurnTokensResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgBurnTokensResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgBurnTokensResponse({ value: MsgBurnTokensResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgBurnTokensResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		queryAllDenomsByAdminRequest({ value }: queryAllDenomsByAdminRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryAllDenomsByAdminRequest", value: QueryAllDenomsByAdminRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllDenomsByAdminRequest: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDenomMaxSupplyResponse({ value }: msgUpdateDenomMaxSupplyResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgUpdateDenomMaxSupplyResponse", value: MsgUpdateDenomMaxSupplyResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDenomMaxSupplyResponse: Could not create message: ' + e.message)
			}
		},
		
		msgBurnTokens({ value }: msgBurnTokensParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgBurnTokens", value: MsgBurnTokens.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgBurnTokens: Could not create message: ' + e.message)
			}
		},
		
		queryDenomByAdminRequest({ value }: queryDenomByAdminRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryDenomByAdminRequest", value: QueryDenomByAdminRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryDenomByAdminRequest: Could not create message: ' + e.message)
			}
		},
		
		queryAllDenomAuthRequest({ value }: queryAllDenomAuthRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryAllDenomAuthRequest", value: QueryAllDenomAuthRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllDenomAuthRequest: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDenomAuth({ value }: msgUpdateDenomAuthParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgUpdateDenomAuth", value: MsgUpdateDenomAuth.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDenomAuth: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDenomUri({ value }: msgUpdateDenomUriParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgUpdateDenomURI", value: MsgUpdateDenomURI.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDenomURI: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDenomMetadataAuth({ value }: msgUpdateDenomMetadataAuthParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgUpdateDenomMetadataAuth", value: MsgUpdateDenomMetadataAuth.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDenomMetadataAuth: Could not create message: ' + e.message)
			}
		},
		
		msgSetDenomMetadataResponse({ value }: msgSetDenomMetadataResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgSetDenomMetadataResponse", value: MsgSetDenomMetadataResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSetDenomMetadataResponse: Could not create message: ' + e.message)
			}
		},
		
		denom({ value }: denomParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.Denom", value: Denom.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Denom: Could not create message: ' + e.message)
			}
		},
		
		queryDenomByAdminResponse({ value }: queryDenomByAdminResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryDenomByAdminResponse", value: QueryDenomByAdminResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryDenomByAdminResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDenomAuthResponse({ value }: msgUpdateDenomAuthResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgUpdateDenomAuthResponse", value: MsgUpdateDenomAuthResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDenomAuthResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDenomMaxSupply({ value }: msgUpdateDenomMaxSupplyParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgUpdateDenomMaxSupply", value: MsgUpdateDenomMaxSupply.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDenomMaxSupply: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDenomMetadataAuthResponse({ value }: msgUpdateDenomMetadataAuthResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgUpdateDenomMetadataAuthResponse", value: MsgUpdateDenomMetadataAuthResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDenomMetadataAuthResponse: Could not create message: ' + e.message)
			}
		},
		
		params({ value }: paramsParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.Params", value: Params.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Params: Could not create message: ' + e.message)
			}
		},
		
		queryGetDenomAuthRequest({ value }: queryGetDenomAuthRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryGetDenomAuthRequest", value: QueryGetDenomAuthRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetDenomAuthRequest: Could not create message: ' + e.message)
			}
		},
		
		msgMintAndSendTokensResponse({ value }: msgMintAndSendTokensResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgMintAndSendTokensResponse", value: MsgMintAndSendTokensResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgMintAndSendTokensResponse: Could not create message: ' + e.message)
			}
		},
		
		msgSetDenomMetadata({ value }: msgSetDenomMetadataParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgSetDenomMetadata", value: MsgSetDenomMetadata.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSetDenomMetadata: Could not create message: ' + e.message)
			}
		},
		
		denomAuth({ value }: denomAuthParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.DenomAuth", value: DenomAuth.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:DenomAuth: Could not create message: ' + e.message)
			}
		},
		
		msgMintAndSendTokens({ value }: msgMintAndSendTokensParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgMintAndSendTokens", value: MsgMintAndSendTokens.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgMintAndSendTokens: Could not create message: ' + e.message)
			}
		},
		
		genesisState({ value }: genesisStateParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.GenesisState", value: GenesisState.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:GenesisState: Could not create message: ' + e.message)
			}
		},
		
		queryAllDenomRequest({ value }: queryAllDenomRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryAllDenomRequest", value: QueryAllDenomRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllDenomRequest: Could not create message: ' + e.message)
			}
		},
		
		queryAllDenomResponse({ value }: queryAllDenomResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryAllDenomResponse", value: QueryAllDenomResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllDenomResponse: Could not create message: ' + e.message)
			}
		},
		
		queryDenomAuthResponse({ value }: queryDenomAuthResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryDenomAuthResponse", value: QueryDenomAuthResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryDenomAuthResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgCreateDenom({ value }: msgCreateDenomParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgCreateDenom", value: MsgCreateDenom.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateDenom: Could not create message: ' + e.message)
			}
		},
		
		msgCreateDenomResponse({ value }: msgCreateDenomResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgCreateDenomResponse", value: MsgCreateDenomResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateDenomResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDenomUriresponse({ value }: msgUpdateDenomUriresponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgUpdateDenomURIResponse", value: MsgUpdateDenomURIResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDenomURIResponse: Could not create message: ' + e.message)
			}
		},
		
		queryParamsResponse({ value }: queryParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryParamsResponse", value: QueryParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetDenomRequest({ value }: queryGetDenomRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryGetDenomRequest", value: QueryGetDenomRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetDenomRequest: Could not create message: ' + e.message)
			}
		},
		
		queryAllDenomsByAdminResponse({ value }: queryAllDenomsByAdminResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryAllDenomsByAdminResponse", value: QueryAllDenomsByAdminResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllDenomsByAdminResponse: Could not create message: ' + e.message)
			}
		},
		
		queryAllDenomAuthResponse({ value }: queryAllDenomAuthResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryAllDenomAuthResponse", value: QueryAllDenomAuthResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllDenomAuthResponse: Could not create message: ' + e.message)
			}
		},
		
		queryParamsRequest({ value }: queryParamsRequestParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryParamsRequest", value: QueryParamsRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsRequest: Could not create message: ' + e.message)
			}
		},
		
		queryDenomResponse({ value }: queryDenomResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.QueryDenomResponse", value: QueryDenomResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryDenomResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParamsResponse({ value }: msgUpdateParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgUpdateParamsResponse", value: MsgUpdateParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		msgBurnTokensResponse({ value }: msgBurnTokensResponseParams): EncodeObject {
			try {
				return { typeUrl: "/zigchain.factory.MsgBurnTokensResponse", value: MsgBurnTokensResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgBurnTokensResponse: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						DenomUnit: getStructure(typeDenomUnit.fromPartial({})),
						Metadata: getStructure(typeMetadata.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			ZigchainFactory: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;